baseURL = 'https://example.org/'
locale = 'en-us'
title = '0xL30'
theme = 'shibui'

[params]
author = "Leonardo Elias"
email = "00xL30@proton.me"

[menu]
[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1
[[menu.main]]
name = "About"
url = "/about/"
weight = 2


[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = false
noClasses = true
tabWidth = 4
style = "algol_nu"
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = true
